### PR TITLE
Refactor and Provide SMTree API

### PR DESCRIPTION
**Pull request by jolestar**
```
fn test_smt() {
        let node_store = InMemoryNodeStore::default();
        let smt = SMTree::new(node_store, None);
        let key = "key";
        let value = "value";
        smt.insert(key.to_string(), value).unwrap();
        smt.get_with_proof(key).unwrap();
        smt.put(key.to_string(), value.to_string());
        smt.commit().unwrap();
        smt.flush().unwrap();
        let (result, proof) = smt.get_with_proof(key.to_string()).unwrap();
        assert_eq!(result.unwrap(), value.to_string());
        assert!(proof
            .verify(smt.root_hash(), key.to_string(), Some(value.to_string()))
            .is_ok());

        let (result, proof) = smt.get_with_proof("key2".to_string()).unwrap();
        assert_eq!(result, None);
        assert!(proof
            .verify::<String, String>(smt.root_hash(), "key2".to_string(), None)
            .is_ok());
}
```

TODO uses batch updates, auto commit&flush when batch update, remove `commit`,`flush` method.

### CODE REVIEW

**Comment by templexxx** [comment]
@jolestar why remove `commit` `flush`? we can auto do that and remain the APIs at the same time

**Comment by jolestar** [comment]
> @jolestar why remove `commit` `flush`? we can auto do that and remain the APIs at the same time

Currently, calling the SMTree `put` method does not immediately update the `state_root`. The state_root is generated during each `commit` and only written to storage during `flush`. 

However, this approach can cause confusion for callers, such as querying immediately after a put. Therefore, I plan to switch to batch puts where each put generates a state_root and writes data to storage. 

But the refactor work may be done in the future, Currently, I just make `commit` and `flush` as internal methods.

**Comment by lshoo** [comment]
cache_guard.split_off_idx = Some(cache_guard.change_set_list.len());

[The line](https://github.com/rooch-network/smt/blob/state_tree/src/lib.rs#L285) is not used in flush function of  lib.rs, and

~~`let change_set_list = self.cache.lock().change_set_list.clone();`~~

**Comment by lshoo** [comment]
> ```
>          cache_guard.split_off_idx = Some(cache_guard.change_set_list.len());
> ```
> 
> [The line](https://github.com/rooch-network/smt/blob/state_tree/src/lib.rs#L285) is not used in flush function of lib.rs, and
> 
> `let change_set_list = self.cache.lock().change_set_list.clone();`

I think the mut cache will be changed after lock()，the change_set_list must be updated while flush the data, the originial code is right.  
please gnore the previous comment, sorry

**Comment by jolestar** [comment]
I merge this PR for the next work, @templexxx @lshoo can review it in the repo.

**Pull request merged**
